### ISSUE TITLE
[v13] Upgrade to be compatible with "debug=1" instead of "debug="

### ISSUE THREAD

**Issue by ray-odoo** [TheBigTester/Odoo-Easy-Debug#1]
These are the DEBUG URL's for v13:

DEVELOPER MODE:
/web?debug=1

WITH ASSETS:
/web?debug=assets

WITH ASSETS and TESTS:
/web?debug=assets,tests

DEACTIVATE:
/web?debug=

Are you able to upgrade this tool?  

As a workaround, double clicking still activates ASSETS debugging in v13 but single click does nothing in v13.

**Comment by TheBigTester** [comment]
The addon is now compatible with V13.
The new version is now on AMO.

**Comment by ray-odoo** [comment]
Thanks for the rapid close!
